workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      vars:
        XCODE_WORKSPACE: "CodeMagicBuild.xcworkspace"  # PUT YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "CodeMagicBuild" # PUT THE NAME OF YOUR SCHEME HERE
        #FCI_CERTIFICATE: Encrypted(...) # PUT THE ENCRYPTED DISTRIBUTION CERTIFICATE HERE
        #FCI_CERTIFICATE_PASSWORD: Encrypted(...) # PUT THE ENCRYPTED CERTIFICATE PASSWORD HERE
        #FCI_PROVISIONING_PROFILE: Encrypted(...) # PUT THE ENCRYPTED PROVISIONING PROFILE HERE
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
    - name: iOS test
      script: |
        xcode-project run-tests \
            --workspace $XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME \
      test_report: build/ios/test/*.xml
      # - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
      #   script: keychain initialize
      # - name: Set up Provisioning profiles from environment variables
      #   script: |
      #     PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
      #     mkdir -p "$PROFILES_HOME"
      #     PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
      #     echo ${FCI_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
      #     echo "Saved provisioning profile $PROFILE_PATH"          
      # - name: Set up signing certificate
      #   script: |
      #     echo $FCI_CERTIFICATE | base64 --decode > /tmp/certificate.p12
      #     keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $FCI_CERTIFICATE_PASSWORD          
      # - name: Increment build number
      #   script: agvtool new-version -all $(($BUILD_NUMBER +1))
      # - name: Set up code signing settings on Xcode project
      #   script: xcode-project use-profiles
      # - name: Build ipa for distribution
      #   script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - leandro.paiva@dynamox.net
      # app_store_connect:
      #   apple_id: your_apple_id@example.com  # PUT YOUR APPLE ID HERE
      #   password: Encrypted(...) # PUT YOUR APP-SPECIFIC-PASSWORD HERE https://support.apple.com/en-us/HT204397
